---
site:
  title: sommerfeld.io Docs
  url: https://www.sommerfeld.io/docs-deprecated
  start_page: kobol-docs::index.adoc
  robots: allow
content:
  branches: HEAD
  sources:
    - url: https://gitlab.com/sommerfeld.sebastian/v-kube-cluster.git
      start_path: docs
      branches: [master, feat/k3s]
    - url: https://gitlab.com/sommerfeld.sebastian/raspi-config.git
      start_path: docs
    - url: https://gitlab.com/sommerfeld.sebastian/docker-jenkins.git
      start_path: docs
    - url: https://gitlab.com/sommerfeld.sebastian/kobol.git
      start_path: docs
    - url: https://gitlab.com/sommerfeld.sebastian/marvin.git
      start_path: docs
    - url: https://github.com/sebastian-sommerfeld-io/kobol-config.git
      start_path: docs
    - url: https://gitlab.com/sommerfeld-io/ui-bundle-docs.git
      start_path: docs
      branches: [master, feat/falcon-theme]
asciidoc:
  attributes:
    # kroki-server-url: http://localhost:7001
    # Use public kroki instead
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # url: https://sommerfeld.jfrog.io/artifactory/default-generic-local/dev/sommerfeld/ui/ui-bundle-docs/ui-bundle-docs-SNAPSHOT.zip
    snapshot: true
  supplemental_files: ./src/main/supplemental-ui
output:
  clean: true
  dir: ./target/docs-deprecated/public
runtime:
  cache_dir: ./target/docs-deprecated/cache/antora
  fetch: true
