---
site:
  title: sommerfeld.io Docs
  url: http://localhost:7888
  start_page: infrastructure-docs::index.adoc
  robots: allow
content:
  branches: HEAD
  sources:
    - url: ../../website-sommerfeld-io
      start_path: subdomain-docs/docs
    - url: ../../website-sommerfeld-io
      start_path: subdomain-www/docs
    - url: ../../infrastructure
      start_path: docs
    - url: ../../playgrounds
      start_path: docs
    - url: ../../../sommerfeld.sebastian/prometheus-grafana
      start_path: docs
    - url: ../../../sommerfeld.sebastian/spring-rest-docs-example
      start_path: docs
asciidoc:
  attributes:
    kroki-server-url: http://localhost:7001
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # url: ../../../sommerfeld-io/ui-bundle-docs/target/build/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: ./target/docs/public
runtime:
  cache_dir: ./target/docs/cache/antora
  fetch: true
