---
site:
  title: sommerfeld.io Docs
  url: https://www.sommerfeld.io/docs
  start_page: infrastructure-docs::index.adoc
  robots: allow
content:
  branches: HEAD
  sources:
    - url: https://github.com/sebastian-sommerfeld-io/website-sommerfeld-io.git
      start_path: subdomain-docs/docs
    - url: https://github.com/sebastian-sommerfeld-io/website-sommerfeld-io.git
      start_path: subdomain-www/docs
    - url: https://gitlab.com/sommerfeld.sebastian/prometheus-grafana.git
      start_path: docs
    - url: https://github.com/sebastian-sommerfeld-io/docker-images.git
      start_path: docs
    - url: https://github.com/sebastian-sommerfeld-io/infrastructure.git
      start_path: docs
    - url: https://github.com/sebastian-sommerfeld-io/playgrounds.git
      start_path: docs
    - url: https://gitlab.com/sommerfeld.sebastian/spring-rest-docs-example.git
      start_path: docs
asciidoc:
  attributes:
    # kroki-server-url: http://localhost:7001
    # Use public kroki instead
    kroki-fetch-diagram: true
  extensions:
    - asciidoctor-kroki
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    # url: https://sommerfeld.jfrog.io/artifactory/default-generic-local/dev/sommerfeld/ui/ui-bundle-docs/ui-bundle-docs-SNAPSHOT.zip
    snapshot: true
  supplemental_files: ./src/main/supplemental-ui
output:
  clean: true
  dir: ./target/docs/public
runtime:
  cache_dir: ./target/docs/cache/antora
  fetch: true
