= run.sh
Jenkins Pipeline <sebastian@sommerfeld.io>
:page-toclevels: 1

Build Docker image containing the whole website and run in container.

== Overview

The script builds a Docker image containing the whole website inside an Apache httpd webserver and runs the image in a container. The base image is the link:https://hub.docker.com/_/httpd[official Apache httpd image].

The script generates all assets for the antora pages as defined in `playbook-*-local.yml` files before the Docker build.

[verse]
--
What | Port | Protocol |
———————————————————————————-–—————————— | —- | ——– |
`kobol/website:unstable` | 9888 | http |
`yuzutech/kroki:latest` (started for antora builds, stopped and removed afterwards) | 9001 | http |
`asciidoctor/docker-asciidoctor:latest` (started to build revealJS landingpage, stopped and removed afterwards) | - | - |
--

The image is intended for local testing purposes. Container is started in foreground.

For production use, take a look at link:https://hub.docker.com/r/sommerfeldio/website[`sommerfeldio/website:latest` on Dockerhub].

=== Arguments

The script does not accept any parameters.

== Index

* link:#_buildantorapages[buildAntoraPages()]
* link:#_buildlandingpage[buildLandingPage()]

== buildAntoraPages()

Build the Antora pages for given playbook.

=== Example

[source,bash]
----
buildAntoraPages "playbook-docs-local.yml"
----

== buildLandingPage()

Build the revealJS landingpage.

=== Example

[source,bash]
----
buildLandingPage
----
